name: E2E Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          targetDate: '2024-09-03'
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-db-id: ${{ secrets.NOTION_DB_ID }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.tweet }}"
